### ISSUE TITLE
高亮bug

### ISSUE THREAD

**Issue by kdurant** [WeiChungWu/vim-SystemVerilog#3]
```systemverilog
    #110us
    spi_write_frame();
    #20us
```

其中#20us是高亮的，#110us无高亮

**Comment by WeiChungWu** [comment]
I try this in my local as below. However it seems normal.
![image](https://cloud.githubusercontent.com/assets/1480935/14666034/adbac20a-0709-11e6-926f-d14645ce5c51.png)

Can you please provide your file that I can reproduce your case?
Thanks!

**Comment by kdurant** [comment]
可能是vim刷新不及时导致的，这会不出现了。

英语不是特别好，一些问题表达不清楚。大陆的输入法一般都不带繁体字的。
抱歉了
